"""Pipeline C: scripts/verify-phase3-software.sh wrapped headlessly (QA-02).

Invokes the existing 8-check bench-smoke script under pytest and asserts:
  1. Exit code 0
  2. The produced 03-08-VERIFY.md report contains a 'PASS' marker

Skips gracefully when ``docker`` is unavailable on the host so the test
suite stays green on lightweight CI runners.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "verify-phase3-software.sh"
VERIFY_MD = REPO_ROOT / ".planning" / "phases" / "03-weather-node" / "03-08-VERIFY.md"


@pytest.mark.integration
@pytest.mark.slow
def test_pipeline_c_verify_phase3_software() -> None:
    if shutil.which("docker") is None:
        pytest.skip("docker not available on host")
    assert SCRIPT.exists(), f"verify script missing: {SCRIPT}"

    proc = subprocess.run(  # nosec B603 B607 — fixed-path bash invocation of repo script
        ["bash", str(SCRIPT)],
        capture_output=True,
        text=True,
        cwd=str(REPO_ROOT),
        timeout=300,
        check=False,
    )

    assert proc.returncode == 0, (
        f"verify-phase3-software.sh failed (exit {proc.returncode}):\n"
        f"STDOUT (tail):\n{proc.stdout[-2000:]}\n"
        f"STDERR (tail):\n{proc.stderr[-2000:]}"
    )

    # Report is generated by the script under .planning/phases/03-weather-node/.
    # If the script ran but the report path moved, prefer the stdout PASS marker
    # rather than failing on absent file.
    if VERIFY_MD.exists():
        report_text = VERIFY_MD.read_text()
        assert "PASS" in report_text, (
            f"03-08-VERIFY.md does not contain a PASS marker:\n{report_text[-1500:]}"
        )
    else:
        # Fallback: assert PASS appears in stdout transcript.
        assert "PASS" in proc.stdout, "Neither 03-08-VERIFY.md nor stdout contains a PASS marker"
